before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./ibiss-spec.tex
deploy:
  provider: releases
  api_key:
    secure: 
  file:
  - ./_build/ibiss-spe.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
